// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SrsDbContext))]
    [Migration("20251228073444_edithod")]
    partial class edithod
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoCalculatedScore", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScoreID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<int>("AcademicAdvisingScore")
                        .HasColumnType("int");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int")
                        .HasColumnName("EvaluationID");

                    b.Property<int>("StudentSurveyScore")
                        .HasColumnType("int");

                    b.Property<int>("TechingLoadCompletionScore")
                        .HasColumnType("int");

                    b.HasKey("ScoreId")
                        .HasName("PK_SystemScores");

                    b.HasIndex(new[] { "EvaluationId" }, "UQ_AutoCalc_EvaluationID")
                        .IsUnique();

                    b.ToTable("AutoCalculatedScores", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EvaluationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationId"));

                    b.Property<DateTime?>("DateApproved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeanReturnComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Dean_ReturnComment");

                    b.Property<string>("FinalGrade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HodReturnComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HOD_ReturnComment");

                    b.Property<string>("HodStrengths")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HOD_Strengths");

                    b.Property<string>("HodWeaknesses")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HOD_Weaknesses");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int")
                        .HasColumnName("PeriodID");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<decimal?>("StudentSurveyScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TaEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("TA_EmployeeID");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("EvaluationId")
                        .HasName("PK__Evaluati__36AE68D38FC7B59C");

                    b.HasIndex("PeriodId");

                    b.HasIndex("StatusId");

                    b.ToTable("Evaluations", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.EvaluationGradeRange", b =>
                {
                    b.Property<int>("RangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RangeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("MaxGrade")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal>("MinGrade")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<DateOnly>("ValidFromDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ValidToDate")
                        .HasColumnType("date");

                    b.HasKey("RangeId")
                        .HasName("PK__Evaluati__6899CAF40A26F490");

                    b.ToTable("EvaluationGradeRange", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.EvaluationPeriod", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PeriodID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("PeriodId")
                        .HasName("PK__Evaluati__E521BB36B76F7D95");

                    b.HasIndex(new[] { "PeriodName" }, "UQ_EvaluationPeriods")
                        .IsUnique();

                    b.ToTable("EvaluationPeriods", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.EvaluationStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusId")
                        .HasName("PK__Evaluati__C8EE2043B4D1D470");

                    b.HasIndex(new[] { "StatusName" }, "UQ_StatusName")
                        .IsUnique();

                    b.ToTable("EvaluationStatuses", "taEvaluation");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            StatusDescription = "NUTA has not submitted their evaluation yet",
                            StatusName = "Draft"
                        },
                        new
                        {
                            StatusId = 2,
                            StatusDescription = "Evaluation submitted by TA and awaiting HOD review",
                            StatusName = "Submitted"
                        },
                        new
                        {
                            StatusId = 3,
                            StatusDescription = "HOD has Returned and provided comments",
                            StatusName = "ReturnedByHOD_ToTA"
                        },
                        new
                        {
                            StatusId = 4,
                            StatusDescription = "HOD returned the evaluation to the Professor for corrections",
                            StatusName = "ReturnedByHOD_ToProfessor"
                        },
                        new
                        {
                            StatusId = 5,
                            StatusDescription = "HOD has reviewed the evaluation And Accept it",
                            StatusName = "AcceptedByHOD"
                        },
                        new
                        {
                            StatusId = 6,
                            StatusDescription = "Evaluation fully approved and completed",
                            StatusName = "Approved"
                        },
                        new
                        {
                            StatusId = 7,
                            StatusDescription = "Dean returned the evaluation for corrections",
                            StatusName = "ReturnedByDean"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.GsdeanEvaluation", b =>
                {
                    b.Property<int>("GsevalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GSEvalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GsevalId"));

                    b.Property<int>("CompletedHours")
                        .HasColumnType("int");

                    b.Property<bool>("DataCollection")
                        .HasColumnType("bit");

                    b.Property<string>("EvaluationComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvaluationPeriodId")
                        .HasColumnType("int")
                        .HasColumnName("EvaluationPeriodID");

                    b.Property<DateOnly>("ExpectedCompletionDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Gpa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GsdeanEmloyeeId")
                        .HasColumnType("int");

                    b.Property<bool>("LiteratureReview")
                        .HasColumnType("bit");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgressScore")
                        .HasColumnType("int");

                    b.Property<bool>("ResearchPlan")
                        .HasColumnType("bit");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int?>("TaEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("TA_EmployeeID");

                    b.Property<bool>("ThesisDefense")
                        .HasColumnType("bit");

                    b.Property<bool>("TopicChosen")
                        .HasColumnType("bit");

                    b.Property<bool>("Writing")
                        .HasColumnType("bit");

                    b.HasKey("GsevalId");

                    b.HasIndex("StatusId");

                    b.HasIndex("EvaluationPeriodId", "TaEmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UQ_GSDean_Period_TA")
                        .HasFilter("[TA_EmployeeID] IS NOT NULL");

                    b.ToTable("GSDean_Evaluations", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.Hodevaluation", b =>
                {
                    b.Property<int>("HodevalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HODEvalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HodevalId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CriterionId")
                        .HasColumnType("int")
                        .HasColumnName("CriterionID");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int")
                        .HasColumnName("EvaluationID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("RatingId")
                        .HasColumnType("int")
                        .HasColumnName("RatingID");

                    b.Property<string>("SourceRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("HOD");

                    b.HasKey("HodevalId")
                        .HasName("PK__HODEvalu__6A4AF4FA7D98075F");

                    b.HasIndex("CriterionId");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("RatingId");

                    b.ToTable("HODEvaluations", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.HodevaluationCriterion", b =>
                {
                    b.Property<int>("CriterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CriterionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriterionId"));

                    b.Property<string>("CriterionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CriterionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CriterionId")
                        .HasName("PK__HODEvalu__647C3BD120762426");

                    b.ToTable("HODEvaluation_Criteria", "taEvaluation");

                    b.HasData(
                        new
                        {
                            CriterionId = 1,
                            CriterionName = "إعداد مذكرات للجزء العملي/تدريبات",
                            CriterionType = "DirectTeaching"
                        },
                        new
                        {
                            CriterionId = 2,
                            CriterionName = "إعداد مساعدات تعليمية وتدريسية جديدة",
                            CriterionType = "DirectTeaching"
                        },
                        new
                        {
                            CriterionId = 3,
                            CriterionName = "المساعدة في إعداد التجارب العملية/التمارين",
                            CriterionType = "DirectTeaching"
                        },
                        new
                        {
                            CriterionId = 4,
                            CriterionName = "المشاركة في تنظيم وإدارة دورات تدريسية/مؤتمرات",
                            CriterionType = "DirectTeaching"
                        },
                        new
                        {
                            CriterionId = 5,
                            CriterionName = "أي نشاط تعليمي آخر مكلف به",
                            CriterionType = "DirectTeaching"
                        },
                        new
                        {
                            CriterionId = 6,
                            CriterionName = "لجنة الإرشاد الأكاديمي",
                            CriterionType = "Administrative"
                        },
                        new
                        {
                            CriterionId = 7,
                            CriterionName = "لجنة الجدولة",
                            CriterionType = "Administrative"
                        },
                        new
                        {
                            CriterionId = 8,
                            CriterionName = "لجنة أعمال الجودة",
                            CriterionType = "Administrative"
                        },
                        new
                        {
                            CriterionId = 9,
                            CriterionName = "لجنة التجهيزات المعملية",
                            CriterionType = "Administrative"
                        },
                        new
                        {
                            CriterionId = 10,
                            CriterionName = "لجنة تنظيم امتحانات",
                            CriterionType = "Administrative"
                        },
                        new
                        {
                            CriterionId = 11,
                            CriterionName = "لجان النشاط الاجتماعي أو الرياضي",
                            CriterionType = "Administrative"
                        },
                        new
                        {
                            CriterionId = 12,
                            CriterionName = "نشاط رياضي",
                            CriterionType = "StudentActivities"
                        },
                        new
                        {
                            CriterionId = 13,
                            CriterionName = "نشاط اجتماعي",
                            CriterionType = "StudentActivities"
                        },
                        new
                        {
                            CriterionId = 14,
                            CriterionName = "نشاط ثقافي",
                            CriterionType = "StudentActivities"
                        },
                        new
                        {
                            CriterionId = 15,
                            CriterionName = "التعاون والعمل الجماعي",
                            CriterionType = "PersonalTraits"
                        },
                        new
                        {
                            CriterionId = 16,
                            CriterionName = "الالتزام بالمواعيد",
                            CriterionType = "PersonalTraits"
                        },
                        new
                        {
                            CriterionId = 17,
                            CriterionName = "المظهر العام",
                            CriterionType = "PersonalTraits"
                        },
                        new
                        {
                            CriterionId = 18,
                            CriterionName = "المبادرة وتحمل المسؤولية",
                            CriterionType = "PersonalTraits"
                        },
                        new
                        {
                            CriterionId = 19,
                            CriterionName = "إدارة الوقت",
                            CriterionType = "PersonalTraits"
                        },
                        new
                        {
                            CriterionId = 20,
                            CriterionName = "تقييم المشاركة في اللجان",
                            CriterionType = "AdministrativeTotal"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E32770FC71F");

                    b.ToTable("Notifications", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.ProfessorCourseEvaluation", b =>
                {
                    b.Property<int>("ProfEvalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProfEvalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfEvalId"));

                    b.Property<int>("AttendanceScore")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("EvaluationPeriodId")
                        .HasColumnType("int")
                        .HasColumnName("EvaluationPeriodID");

                    b.Property<string>("HodReturnComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HOD_ReturnComment");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<int>("OfficeHoursScore")
                        .HasColumnType("int");

                    b.Property<int>("PerformanceScore")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Professor_EmployeeID");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int>("TaEmployeeId")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("TA_EmployeeID")
                        .IsFixedLength();

                    b.Property<int?>("TotalScore")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(([OfficeHoursScore]+[AttendanceScore])+[PerformanceScore])", false);

                    b.HasKey("ProfEvalId")
                        .HasName("PK__Professo__DACBBA357239488F");

                    b.HasIndex("EvaluationPeriodId");

                    b.HasIndex("StatusId");

                    b.ToTable("ProfessorCourseEvaluations", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RatingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<string>("RatingName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ScoreValue")
                        .HasColumnType("int");

                    b.HasKey("RatingId")
                        .HasName("PK__Ratings__FCCDF85CD6813305");

                    b.HasIndex(new[] { "RatingName" }, "UQ_RatingName")
                        .IsUnique();

                    b.ToTable("Ratings", "taEvaluation");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            RatingName = "TA_ضعيف",
                            ScoreValue = 0
                        },
                        new
                        {
                            RatingId = 2,
                            RatingName = "TA_مقبول",
                            ScoreValue = 1
                        },
                        new
                        {
                            RatingId = 3,
                            RatingName = "TA_جيد",
                            ScoreValue = 2
                        },
                        new
                        {
                            RatingId = 4,
                            RatingName = "TA_جيد جداً",
                            ScoreValue = 3
                        },
                        new
                        {
                            RatingId = 5,
                            RatingName = "TA_ممتاز",
                            ScoreValue = 4
                        },
                        new
                        {
                            RatingId = 6,
                            RatingName = "SA_ضعيف",
                            ScoreValue = 0
                        },
                        new
                        {
                            RatingId = 7,
                            RatingName = "SA_مقبول",
                            ScoreValue = 1
                        },
                        new
                        {
                            RatingId = 8,
                            RatingName = "SA_جيد",
                            ScoreValue = 2
                        },
                        new
                        {
                            RatingId = 9,
                            RatingName = "SA_جيد جداً",
                            ScoreValue = 3
                        },
                        new
                        {
                            RatingId = 10,
                            RatingName = "SA_ممتاز",
                            ScoreValue = 4
                        },
                        new
                        {
                            RatingId = 11,
                            RatingName = "PT_ضعيف",
                            ScoreValue = 0
                        },
                        new
                        {
                            RatingId = 12,
                            RatingName = "PT_مقبول",
                            ScoreValue = 1
                        },
                        new
                        {
                            RatingId = 13,
                            RatingName = "PT_جيد",
                            ScoreValue = 2
                        },
                        new
                        {
                            RatingId = 14,
                            RatingName = "PT_جيد جداً",
                            ScoreValue = 3
                        },
                        new
                        {
                            RatingId = 15,
                            RatingName = "PT_ممتاز",
                            ScoreValue = 4
                        },
                        new
                        {
                            RatingId = 16,
                            RatingName = "Admin_0",
                            ScoreValue = 0
                        },
                        new
                        {
                            RatingId = 17,
                            RatingName = "Admin_1",
                            ScoreValue = 1
                        },
                        new
                        {
                            RatingId = 18,
                            RatingName = "Admin_2",
                            ScoreValue = 2
                        },
                        new
                        {
                            RatingId = 19,
                            RatingName = "Admin_3",
                            ScoreValue = 3
                        },
                        new
                        {
                            RatingId = 20,
                            RatingName = "Admin_4",
                            ScoreValue = 4
                        },
                        new
                        {
                            RatingId = 21,
                            RatingName = "Admin_5",
                            ScoreValue = 5
                        },
                        new
                        {
                            RatingId = 22,
                            RatingName = "Admin_6",
                            ScoreValue = 6
                        },
                        new
                        {
                            RatingId = 23,
                            RatingName = "Admin_7",
                            ScoreValue = 7
                        },
                        new
                        {
                            RatingId = 24,
                            RatingName = "Admin_8",
                            ScoreValue = 8
                        },
                        new
                        {
                            RatingId = 25,
                            RatingName = "Admin_9",
                            ScoreValue = 9
                        },
                        new
                        {
                            RatingId = 26,
                            RatingName = "Admin_10",
                            ScoreValue = 10
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.ReminderLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int")
                        .HasColumnName("EvaluationID");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("RecievedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("RecievedBy_EmployeeID");

                    b.Property<string>("RecipientDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SentByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("SentBy_EmployeeID");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LogId")
                        .HasName("PK__Reminder__5E5499A89B61C1AD");

                    b.HasIndex("EvaluationId");

                    b.ToTable("ReminderLogs", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.ResearchActivity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActivityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<DateOnly>("ActivityDate")
                        .HasColumnType("date");

                    b.Property<string>("Journal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int")
                        .HasColumnName("SubmissionID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("URL");

                    b.HasKey("ActivityId")
                        .HasName("PK__Research__45F4A7F1FF725F51");

                    b.HasIndex("StatusId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("ResearchActivities", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.ResearchStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusKey")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusId")
                        .HasName("PK__Research__C8EE204312F7CC6C");

                    b.HasIndex(new[] { "StatusKey" }, "UQ__Research__096C98C29B241A88")
                        .IsUnique();

                    b.ToTable("ResearchStatuses", "taEvaluation");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            StatusKey = "P",
                            StatusName = "Published"
                        },
                        new
                        {
                            StatusId = 2,
                            StatusKey = "S",
                            StatusName = "Submitted"
                        },
                        new
                        {
                            StatusId = 3,
                            StatusKey = "R",
                            StatusName = "Rejected"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Tasubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubmissionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<int>("ActualTeachingLoad")
                        .HasColumnType("int");

                    b.Property<int?>("AdvisedStudentCount")
                        .HasColumnType("int");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int")
                        .HasColumnName("EvaluationID");

                    b.Property<int>("ExpectedTeachingLoad")
                        .HasColumnType("int");

                    b.Property<bool>("HasAttendingSeminars")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSeminarLectures")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTechnicalReports")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInAcademicAdvisingCommittee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInExamOrganizationCommittee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInLabEquipmentCommittee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInQualityAssuranceCommittee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInSchedulingCommittee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInSocialOrSportsCommittee")
                        .HasColumnType("bit");

                    b.Property<bool>("ParticipatedInCultural")
                        .HasColumnType("bit");

                    b.Property<bool>("ParticipatedInSocial")
                        .HasColumnType("bit");

                    b.Property<bool>("ParticipatedInSports")
                        .HasColumnType("bit");

                    b.HasKey("SubmissionId")
                        .HasName("PK__TASubmis__449EE1055BF179B8");

                    b.HasIndex(new[] { "EvaluationId" }, "UQ__TASubmis__36AE68D2799DBF4B")
                        .IsUnique();

                    b.ToTable("TASubmissions", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.VpgsEvaluation", b =>
                {
                    b.Property<int>("VpgsevalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VPGSEvalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VpgsevalId"));

                    b.Property<int?>("EvaluationId")
                        .HasColumnType("int")
                        .HasColumnName("EvaluationID");

                    b.Property<decimal>("ScientificScore")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.HasKey("VpgsevalId")
                        .HasName("PK__VPGS_Eva__57C1D3BEE96AAFED");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "EvaluationId" }, "UQ__VPGS_Eva__36AE68D2910EDF18")
                        .IsUnique()
                        .HasFilter("[EvaluationID] IS NOT NULL");

                    b.ToTable("VPGS_Evaluations", "taEvaluation");
                });

            modelBuilder.Entity("AutoCalculatedScore", b =>
                {
                    b.HasOne("DataAccess.Entities.Evaluation", "Evaluation")
                        .WithOne("AutoCalculatedScore")
                        .HasForeignKey("AutoCalculatedScore", "EvaluationId")
                        .IsRequired()
                        .HasConstraintName("FK_AutoCalculatedScores_Evaluations");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.Evaluation", b =>
                {
                    b.HasOne("DataAccess.Entities.EvaluationPeriod", "Period")
                        .WithMany("Evaluations")
                        .HasForeignKey("PeriodId")
                        .IsRequired()
                        .HasConstraintName("FK_Evaluations_PeriodID");

                    b.HasOne("DataAccess.Entities.EvaluationStatus", "Status")
                        .WithMany("Evaluations")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Evaluations_StatusID");

                    b.Navigation("Period");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DataAccess.Entities.GsdeanEvaluation", b =>
                {
                    b.HasOne("DataAccess.Entities.EvaluationPeriod", "EvaluationPeriod")
                        .WithMany("GsdeanEvaluations")
                        .HasForeignKey("EvaluationPeriodId")
                        .IsRequired()
                        .HasConstraintName("FK_GSDean_Evaluations_EvaluationPeriodID");

                    b.HasOne("DataAccess.Entities.EvaluationStatus", "Status")
                        .WithMany("GsdeanEvaluations")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_GSDean_Evaluations_StatusID");

                    b.Navigation("EvaluationPeriod");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DataAccess.Entities.Hodevaluation", b =>
                {
                    b.HasOne("DataAccess.Entities.HodevaluationCriterion", "Criterion")
                        .WithMany("Hodevaluations")
                        .HasForeignKey("CriterionId")
                        .IsRequired()
                        .HasConstraintName("FK_HODEvaluations_CriterionID");

                    b.HasOne("DataAccess.Entities.Evaluation", "Evaluation")
                        .WithMany("Hodevaluations")
                        .HasForeignKey("EvaluationId")
                        .IsRequired()
                        .HasConstraintName("FK_HODEvaluations_EvaluationID");

                    b.HasOne("DataAccess.Entities.Rating", "Rating")
                        .WithMany("Hodevaluations")
                        .HasForeignKey("RatingId")
                        .IsRequired()
                        .HasConstraintName("FK_HODEvaluations_RatingID");

                    b.Navigation("Criterion");

                    b.Navigation("Evaluation");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("DataAccess.Entities.ProfessorCourseEvaluation", b =>
                {
                    b.HasOne("DataAccess.Entities.EvaluationPeriod", "EvaluationPeriod")
                        .WithMany("ProfessorCourseEvaluations")
                        .HasForeignKey("EvaluationPeriodId")
                        .IsRequired()
                        .HasConstraintName("FK_ProfessorCourseEvaluations_EvaluationPeriods");

                    b.HasOne("DataAccess.Entities.EvaluationStatus", "Status")
                        .WithMany("ProfessorCourseEvaluations")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_ProfessorCourseEvaluations_EvaluationStatuses");

                    b.Navigation("EvaluationPeriod");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DataAccess.Entities.ReminderLog", b =>
                {
                    b.HasOne("DataAccess.Entities.Evaluation", "Evaluation")
                        .WithMany("ReminderLogs")
                        .HasForeignKey("EvaluationId")
                        .IsRequired()
                        .HasConstraintName("FK_ReminderLogs_EvaluationID");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.ResearchActivity", b =>
                {
                    b.HasOne("DataAccess.Entities.ResearchStatus", "Status")
                        .WithMany("ResearchActivities")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_ResearchActivities_StatusID");

                    b.HasOne("DataAccess.Entities.Tasubmission", "Submission")
                        .WithMany("ResearchActivities")
                        .HasForeignKey("SubmissionId")
                        .IsRequired()
                        .HasConstraintName("FK_ResearchActivities_SubmissionID");

                    b.Navigation("Status");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("DataAccess.Entities.Tasubmission", b =>
                {
                    b.HasOne("DataAccess.Entities.Evaluation", "Evaluation")
                        .WithOne("Tasubmission")
                        .HasForeignKey("DataAccess.Entities.Tasubmission", "EvaluationId")
                        .IsRequired()
                        .HasConstraintName("FK_TA_Submissions_EvaluationID");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.VpgsEvaluation", b =>
                {
                    b.HasOne("DataAccess.Entities.Evaluation", "Evaluation")
                        .WithOne("EvaluationNavigation")
                        .HasForeignKey("DataAccess.Entities.VpgsEvaluation", "EvaluationId");

                    b.HasOne("DataAccess.Entities.EvaluationStatus", "Status")
                        .WithMany("VpgsEvaluations")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_VPGS_Evaluations_EvaluationStatuses");

                    b.Navigation("Evaluation");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DataAccess.Entities.Evaluation", b =>
                {
                    b.Navigation("AutoCalculatedScore");

                    b.Navigation("EvaluationNavigation")
                        .IsRequired();

                    b.Navigation("Hodevaluations");

                    b.Navigation("ReminderLogs");

                    b.Navigation("Tasubmission");
                });

            modelBuilder.Entity("DataAccess.Entities.EvaluationPeriod", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("GsdeanEvaluations");

                    b.Navigation("ProfessorCourseEvaluations");
                });

            modelBuilder.Entity("DataAccess.Entities.EvaluationStatus", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("GsdeanEvaluations");

                    b.Navigation("ProfessorCourseEvaluations");

                    b.Navigation("VpgsEvaluations");
                });

            modelBuilder.Entity("DataAccess.Entities.HodevaluationCriterion", b =>
                {
                    b.Navigation("Hodevaluations");
                });

            modelBuilder.Entity("DataAccess.Entities.Rating", b =>
                {
                    b.Navigation("Hodevaluations");
                });

            modelBuilder.Entity("DataAccess.Entities.ResearchStatus", b =>
                {
                    b.Navigation("ResearchActivities");
                });

            modelBuilder.Entity("DataAccess.Entities.Tasubmission", b =>
                {
                    b.Navigation("ResearchActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
