// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SrsDbContext))]
    [Migration("20251203125740_Fix_GSDean_Relationship")]
    partial class Fix_GSDean_Relationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EvaluationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationId"));

                    b.Property<DateTime?>("DateApproved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeanReturnComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Dean_ReturnComment");

                    b.Property<string>("FinalGrade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HodReturnComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HOD_ReturnComment");

                    b.Property<string>("HodStrengths")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HOD_Strengths");

                    b.Property<string>("HodWeaknesses")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HOD_Weaknesses");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int")
                        .HasColumnName("PeriodID");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<decimal?>("StudentSurveyScore")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<int>("TaEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("TA_EmployeeID");

                    b.HasKey("EvaluationId")
                        .HasName("PK__Evaluati__36AE68D3DC67C19C");

                    b.HasIndex("PeriodId");

                    b.HasIndex("StatusId");

                    b.ToTable("Evaluations", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.EvaluationPeriod", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PeriodID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("PeriodId")
                        .HasName("PK__Evaluati__E521BB36E10D5CDC");

                    b.HasIndex(new[] { "PeriodName" }, "UQ__Evaluati__D748F8F21DD95950")
                        .IsUnique();

                    b.ToTable("EvaluationPeriods", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.EvaluationStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusId")
                        .HasName("PK__Evaluati__C8EE20437A4A7778");

                    b.HasIndex(new[] { "StatusName" }, "UQ__Evaluati__05E7698A9628677D")
                        .IsUnique();

                    b.ToTable("EvaluationStatuses", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.GsdeanEvaluation", b =>
                {
                    b.Property<int>("GsevalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GSEvalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GsevalId"));

                    b.Property<int>("CompletedHours")
                        .HasColumnType("int");

                    b.Property<bool>("DataCollection")
                        .HasColumnType("bit");

                    b.Property<string>("EvaluationComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvaluationPeriodId")
                        .HasColumnType("int")
                        .HasColumnName("EvaluationPeriodID");

                    b.Property<DateOnly>("ExpectedCompletionDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Gpa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GsdeanEmloyeeId")
                        .HasColumnType("int");

                    b.Property<bool>("LiteratureReview")
                        .HasColumnType("bit");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProgressScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ResearchPlan")
                        .HasColumnType("bit");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int?>("TaEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("TA_EmployeeID");

                    b.Property<bool>("ThesisDefense")
                        .HasColumnType("bit");

                    b.Property<bool>("TopicChosen")
                        .HasColumnType("bit");

                    b.Property<bool>("Writing")
                        .HasColumnType("bit");

                    b.HasKey("GsevalId");

                    b.HasIndex("StatusId");

                    b.HasIndex("EvaluationPeriodId", "TaEmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UQ_GSDean_Period_TA")
                        .HasFilter("[TA_EmployeeID] IS NOT NULL");

                    b.ToTable("GSDean_Evaluations", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.Hodevaluation", b =>
                {
                    b.Property<int>("HodevalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HODEvalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HodevalId"));

                    b.Property<int>("CriterionId")
                        .HasColumnType("int")
                        .HasColumnName("CriterionID");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int")
                        .HasColumnName("EvaluationID");

                    b.Property<int>("RatingId")
                        .HasColumnType("int")
                        .HasColumnName("RatingID");

                    b.HasKey("HodevalId")
                        .HasName("PK__HODEvalu__6A4AF4FAEBE6B771");

                    b.HasIndex("CriterionId");

                    b.HasIndex("RatingId");

                    b.HasIndex(new[] { "EvaluationId", "CriterionId" }, "UQ_HODEvaluations")
                        .IsUnique();

                    b.ToTable("HODEvaluations", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.HodevaluationCriterion", b =>
                {
                    b.Property<int>("CriterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CriterionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriterionId"));

                    b.Property<string>("CriterionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CriterionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CriterionId")
                        .HasName("PK__HODEvalu__647C3BD119DF663C");

                    b.ToTable("HODEvaluation_Criteria", "taEvaluation");

                    b.HasData(
                        new
                        {
                            CriterionId = 1,
                            CriterionName = "إعداد مذكرات للجزء العملي/تدريبات",
                            CriterionType = "DirectTeaching"
                        },
                        new
                        {
                            CriterionId = 2,
                            CriterionName = "إعداد مساعدات تعليمية وتدريسية جديدة",
                            CriterionType = "DirectTeaching"
                        },
                        new
                        {
                            CriterionId = 3,
                            CriterionName = "المساعدة في إعداد التجارب العملية/التمارين",
                            CriterionType = "DirectTeaching"
                        },
                        new
                        {
                            CriterionId = 4,
                            CriterionName = "المشاركة في تنظيم وإدارة دورات تدريسية/مؤتمرات",
                            CriterionType = "DirectTeaching"
                        },
                        new
                        {
                            CriterionId = 5,
                            CriterionName = "أي نشاط تعليمي آخر مكلف به",
                            CriterionType = "DirectTeaching"
                        },
                        new
                        {
                            CriterionId = 6,
                            CriterionName = "لجنة الإرشاد الأكاديمي",
                            CriterionType = "Administrative"
                        },
                        new
                        {
                            CriterionId = 7,
                            CriterionName = "لجنة الجدولة",
                            CriterionType = "Administrative"
                        },
                        new
                        {
                            CriterionId = 8,
                            CriterionName = "لجنة أعمال الجودة",
                            CriterionType = "Administrative"
                        },
                        new
                        {
                            CriterionId = 9,
                            CriterionName = "لجنة التجهيزات المعملية",
                            CriterionType = "Administrative"
                        },
                        new
                        {
                            CriterionId = 10,
                            CriterionName = "لجنة تنظيم امتحانات",
                            CriterionType = "Administrative"
                        },
                        new
                        {
                            CriterionId = 11,
                            CriterionName = "لجان النشاط الاجتماعي أو الرياضي",
                            CriterionType = "Administrative"
                        },
                        new
                        {
                            CriterionId = 12,
                            CriterionName = "نشاط رياضي",
                            CriterionType = "StudentActivities"
                        },
                        new
                        {
                            CriterionId = 13,
                            CriterionName = "نشاط اجتماعي",
                            CriterionType = "StudentActivities"
                        },
                        new
                        {
                            CriterionId = 14,
                            CriterionName = "نشاط ثقافي",
                            CriterionType = "StudentActivities"
                        },
                        new
                        {
                            CriterionId = 15,
                            CriterionName = "التعاون والعمل الجماعي",
                            CriterionType = "PersonalTraits"
                        },
                        new
                        {
                            CriterionId = 16,
                            CriterionName = "الالتزام بالمواعيد",
                            CriterionType = "PersonalTraits"
                        },
                        new
                        {
                            CriterionId = 17,
                            CriterionName = "المظهر العام",
                            CriterionType = "PersonalTraits"
                        },
                        new
                        {
                            CriterionId = 18,
                            CriterionName = "المبادرة وتحمل المسؤولية",
                            CriterionType = "PersonalTraits"
                        },
                        new
                        {
                            CriterionId = 19,
                            CriterionName = "إدارة الوقت",
                            CriterionType = "PersonalTraits"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E3254FA65A4");

                    b.ToTable("Notifications", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.ProfessorCourseEvaluation", b =>
                {
                    b.Property<int>("ProfEvalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProfEvalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfEvalId"));

                    b.Property<int>("AttendanceScore")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("EvaluationPeriodId")
                        .HasColumnType("int")
                        .HasColumnName("EvaluationPeriodID");

                    b.Property<string>("HodReturnComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HOD_ReturnComment");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<int>("OfficeHoursScore")
                        .HasColumnType("int");

                    b.Property<int>("PerformanceScore")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Professor_EmployeeID");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int>("TaEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("TA_EmployeeID");

                    b.Property<int?>("TotalScore")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(([OfficeHoursScore]+[AttendanceScore])+[PerformanceScore])", false);

                    b.HasKey("ProfEvalId")
                        .HasName("PK__Professo__DACBBA35DF4A614E");

                    b.HasIndex("EvaluationPeriodId");

                    b.HasIndex("StatusId");

                    b.ToTable("ProfessorCourseEvaluations", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RatingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<string>("RatingName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ScoreValue")
                        .HasColumnType("int");

                    b.HasKey("RatingId")
                        .HasName("PK__Ratings__FCCDF85C285DEC07");

                    b.HasIndex(new[] { "RatingName" }, "UQ__Ratings__F7CF97379B70F7DF")
                        .IsUnique();

                    b.ToTable("Ratings", "taEvaluation");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            RatingName = "ممتاز",
                            ScoreValue = 5
                        },
                        new
                        {
                            RatingId = 2,
                            RatingName = "جيد جداً",
                            ScoreValue = 4
                        },
                        new
                        {
                            RatingId = 3,
                            RatingName = "جيد",
                            ScoreValue = 3
                        },
                        new
                        {
                            RatingId = 4,
                            RatingName = "مقبول",
                            ScoreValue = 2
                        },
                        new
                        {
                            RatingId = 5,
                            RatingName = "ضعيف",
                            ScoreValue = 1
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.ReminderLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int")
                        .HasColumnName("EvaluationID");

                    b.Property<int>("RecievedByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("RecievedBy_EmployeeID");

                    b.Property<string>("RecipientDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SentByEmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("SentBy_EmployeeID");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LogId")
                        .HasName("PK__Reminder__5E5499A80E5A40CB");

                    b.HasIndex("EvaluationId");

                    b.ToTable("ReminderLogs", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.ResearchActivity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActivityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<DateOnly>("ActivityDate")
                        .HasColumnType("date");

                    b.Property<string>("Journal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int")
                        .HasColumnName("SubmissionID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("URL");

                    b.HasKey("ActivityId")
                        .HasName("PK__Research__45F4A7F1C12D163E");

                    b.HasIndex("StatusId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("ResearchActivities", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.ResearchStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusKey")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusId")
                        .HasName("PK__Research__C8EE20431C47CE6C");

                    b.HasIndex(new[] { "StatusKey" }, "UQ__Research__096C98C27DE9011A")
                        .IsUnique();

                    b.ToTable("ResearchStatuses", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.Tasubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubmissionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<int>("ActualTeachingLoad")
                        .HasColumnType("int");

                    b.Property<int?>("AdvisedStudentCount")
                        .HasColumnType("int");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int")
                        .HasColumnName("EvaluationID");

                    b.Property<int>("ExpectedTeachingLoad")
                        .HasColumnType("int");

                    b.Property<bool>("HasAttendingSeminars")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSeminarLectures")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTechnicalReports")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInAcademicAdvisingCommittee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInExamOrganizationCommittee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInLabEquipmentCommittee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInQualityAssuranceCommittee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInSchedulingCommittee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInSocialOrSportsCommittee")
                        .HasColumnType("bit");

                    b.Property<bool>("ParticipatedInCultural")
                        .HasColumnType("bit");

                    b.Property<bool>("ParticipatedInSocial")
                        .HasColumnType("bit");

                    b.Property<bool>("ParticipatedInSports")
                        .HasColumnType("bit");

                    b.HasKey("SubmissionId")
                        .HasName("PK__TASubmis__449EE105411A67B0");

                    b.HasIndex(new[] { "EvaluationId" }, "UQ__TASubmis__36AE68D20234AA6E")
                        .IsUnique();

                    b.ToTable("TASubmissions", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.VpgsEvaluation", b =>
                {
                    b.Property<int>("VpgsevalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VPGSEvalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VpgsevalId"));

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int")
                        .HasColumnName("EvaluationID");

                    b.Property<decimal>("ScientificScore")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.HasKey("VpgsevalId")
                        .HasName("PK__VPGS_Eva__57C1D3BEE96AAFED");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "EvaluationId" }, "UQ__VPGS_Eva__36AE68D2910EDF18")
                        .IsUnique();

                    b.ToTable("VPGS_Evaluations", "taEvaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.Evaluation", b =>
                {
                    b.HasOne("DataAccess.Entities.EvaluationPeriod", "Period")
                        .WithMany("Evaluations")
                        .HasForeignKey("PeriodId")
                        .IsRequired()
                        .HasConstraintName("FK_Evaluations_PeriodID");

                    b.HasOne("DataAccess.Entities.EvaluationStatus", "Status")
                        .WithMany("Evaluations")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Evaluations_StatusID");

                    b.Navigation("Period");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DataAccess.Entities.GsdeanEvaluation", b =>
                {
                    b.HasOne("DataAccess.Entities.EvaluationPeriod", "EvaluationPeriod")
                        .WithMany("GsdeanEvaluations")
                        .HasForeignKey("EvaluationPeriodId")
                        .IsRequired()
                        .HasConstraintName("FK_GSDean_Evaluations_EvaluationPeriodID");

                    b.HasOne("DataAccess.Entities.EvaluationStatus", "Status")
                        .WithMany("GsdeanEvaluations")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_GSDean_Evaluations_StatusID");

                    b.Navigation("EvaluationPeriod");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DataAccess.Entities.Hodevaluation", b =>
                {
                    b.HasOne("DataAccess.Entities.HodevaluationCriterion", "Criterion")
                        .WithMany("Hodevaluations")
                        .HasForeignKey("CriterionId")
                        .IsRequired()
                        .HasConstraintName("FK_HODEvaluations_CriterionID");

                    b.HasOne("DataAccess.Entities.Evaluation", "Evaluation")
                        .WithMany("Hodevaluations")
                        .HasForeignKey("EvaluationId")
                        .IsRequired()
                        .HasConstraintName("FK_HODEvaluations_EvaluationID");

                    b.HasOne("DataAccess.Entities.Rating", "Rating")
                        .WithMany("Hodevaluations")
                        .HasForeignKey("RatingId")
                        .IsRequired()
                        .HasConstraintName("FK_HODEvaluations_RatingID");

                    b.Navigation("Criterion");

                    b.Navigation("Evaluation");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("DataAccess.Entities.ProfessorCourseEvaluation", b =>
                {
                    b.HasOne("DataAccess.Entities.EvaluationPeriod", "EvaluationPeriod")
                        .WithMany("ProfessorCourseEvaluations")
                        .HasForeignKey("EvaluationPeriodId")
                        .IsRequired()
                        .HasConstraintName("FK_ProfessorCourseEvaluations_EvaluationPeriodID");

                    b.HasOne("DataAccess.Entities.EvaluationStatus", "Status")
                        .WithMany("ProfessorCourseEvaluations")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_ProfessorCourseEvaluations_StatusID");

                    b.Navigation("EvaluationPeriod");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DataAccess.Entities.ReminderLog", b =>
                {
                    b.HasOne("DataAccess.Entities.Evaluation", "Evaluation")
                        .WithMany("ReminderLogs")
                        .HasForeignKey("EvaluationId")
                        .IsRequired()
                        .HasConstraintName("FK_ReminderLogs_EvaluationID");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.ResearchActivity", b =>
                {
                    b.HasOne("DataAccess.Entities.ResearchStatus", "Status")
                        .WithMany("ResearchActivities")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_ResearchActivities_StatusID");

                    b.HasOne("DataAccess.Entities.Tasubmission", "Submission")
                        .WithMany("ResearchActivities")
                        .HasForeignKey("SubmissionId")
                        .IsRequired()
                        .HasConstraintName("FK_ResearchActivities_SubmissionID");

                    b.Navigation("Status");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("DataAccess.Entities.Tasubmission", b =>
                {
                    b.HasOne("DataAccess.Entities.Evaluation", "Evaluation")
                        .WithOne("Tasubmission")
                        .HasForeignKey("DataAccess.Entities.Tasubmission", "EvaluationId")
                        .IsRequired()
                        .HasConstraintName("FK_TA_Submissions_EvaluationID");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("DataAccess.Entities.VpgsEvaluation", b =>
                {
                    b.HasOne("DataAccess.Entities.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.EvaluationStatus", "Status")
                        .WithMany("VpgsEvaluations")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_VPGS_Evaluations_StatusID");

                    b.Navigation("Evaluation");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DataAccess.Entities.Evaluation", b =>
                {
                    b.Navigation("Hodevaluations");

                    b.Navigation("ReminderLogs");

                    b.Navigation("Tasubmission");
                });

            modelBuilder.Entity("DataAccess.Entities.EvaluationPeriod", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("GsdeanEvaluations");

                    b.Navigation("ProfessorCourseEvaluations");
                });

            modelBuilder.Entity("DataAccess.Entities.EvaluationStatus", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("GsdeanEvaluations");

                    b.Navigation("ProfessorCourseEvaluations");

                    b.Navigation("VpgsEvaluations");
                });

            modelBuilder.Entity("DataAccess.Entities.HodevaluationCriterion", b =>
                {
                    b.Navigation("Hodevaluations");
                });

            modelBuilder.Entity("DataAccess.Entities.Rating", b =>
                {
                    b.Navigation("Hodevaluations");
                });

            modelBuilder.Entity("DataAccess.Entities.ResearchStatus", b =>
                {
                    b.Navigation("ResearchActivities");
                });

            modelBuilder.Entity("DataAccess.Entities.Tasubmission", b =>
                {
                    b.Navigation("ResearchActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
